baseURL = "https://www.keithgramila.com/"
languageCode = "en-us"
title = "KPG Pacific Crest Trail"
theme = "base"
timeout = 180000
[params]
    button = "Go Home"
    description = "Through-hiking the Pacific Crest Trail in 2021. Gear and vibes."
    images = ["keith.png"]
    buttonLink = "/"
[imaging]
    quality = 95
