baseURL = "https://www.keithgramila.com/"
languageCode = "en-us"
title = "KPG Pacific Crest Trail"
theme = "base"
[params]
    start = 2021-03-20T00:00:00.00Z
    button = "Go Back Home"
    buttonLink = "/"
[imaging]
    quality = 95