backend:
  name: git-gateway
  branch: main
media_folder: static/images
public_folder: /images
logo_url: 'https://www.keithgramila.com/keith.png'
collections:
  - name: 'reports'
    label: 'Day Report'
    folder: 'content/{{year}}/{{slug}}'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    slug: '{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Override Date', name: 'overrideDate', widget: 'datetime', required: false, default: '' }
      - { label: 'Title', name: 'title', widget: 'string', pattern: ['^.{1,230}$', "Must be less than 230 characters."] }
      - { label: 'Body', name: 'body', widget: 'markdown'}
